/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LogisticsManager } from "./LogisticsManager";
export type { MineralRegistry } from "./MineralRegistry";
export type { MineralWarehouse } from "./MineralWarehouse";
