/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace RolesManager {
  export type MineralHistoryStruct = {
    id: string;
    fieldChanged: string;
    newValue: string;
    updatedBy: AddressLike;
    timestamp: BigNumberish;
  };

  export type MineralHistoryStructOutput = [
    id: string,
    fieldChanged: string,
    newValue: string,
    updatedBy: string,
    timestamp: bigint
  ] & {
    id: string;
    fieldChanged: string;
    newValue: string;
    updatedBy: string;
    timestamp: bigint;
  };
}

export declare namespace LogisticsManager {
  export type TransportDetailsStruct = {
    mineralId: string;
    requester: AddressLike;
    transporter: AddressLike;
    origin: string;
    destination: string;
    estimatedDeparture: BigNumberish;
    actualDeparture: BigNumberish;
    estimatedArrival: BigNumberish;
    actualArrival: BigNumberish;
    currentStatus: string;
    transportConditions: string;
  };

  export type TransportDetailsStructOutput = [
    mineralId: string,
    requester: string,
    transporter: string,
    origin: string,
    destination: string,
    estimatedDeparture: bigint,
    actualDeparture: bigint,
    estimatedArrival: bigint,
    actualArrival: bigint,
    currentStatus: string,
    transportConditions: string
  ] & {
    mineralId: string;
    requester: string;
    transporter: string;
    origin: string;
    destination: string;
    estimatedDeparture: bigint;
    actualDeparture: bigint;
    estimatedArrival: bigint;
    actualArrival: bigint;
    currentStatus: string;
    transportConditions: string;
  };
}

export interface LogisticsManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AUDITOR_ROLE"
      | "BUYER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "INSPECTOR_ROLE"
      | "MINER_ROLE"
      | "REFINER_ROLE"
      | "TRANSPORTER_ROLE"
      | "_auditMineral"
      | "assignAuditor"
      | "assignBuyer"
      | "assignInspector"
      | "assignMiner"
      | "assignRefiner"
      | "assignTransporter(string,address,uint256)"
      | "assignTransporter(address)"
      | "checkAuditAndInspectionStatus"
      | "completeTransport"
      | "createTransportRequest"
      | "getAllRoleCounts"
      | "getMineralHistory"
      | "getRoleAdmin"
      | "getRoleMemberCount"
      | "getRolesForAddress"
      | "getTransportDetails"
      | "getTransportStatus"
      | "getTransporterAssignments"
      | "grantRole"
      | "hasAdminRole"
      | "hasAuditorRole"
      | "hasBuyerRole"
      | "hasInspectorRole"
      | "hasMinerRole"
      | "hasRefinerRole"
      | "hasRole"
      | "hasTransporterRole"
      | "inspectMineral"
      | "isMineralRegistered"
      | "mineralDetails"
      | "mineralHistories"
      | "purchaseMineral"
      | "refineMineral"
      | "registerMineral"
      | "renounceRole"
      | "revokeAuditor"
      | "revokeBuyer"
      | "revokeInspector"
      | "revokeMiner"
      | "revokeRefiner"
      | "revokeRole"
      | "revokeTransporter"
      | "roleMemberCount"
      | "startTransport"
      | "supportsInterface"
      | "transferMineral"
      | "transportDetails"
      | "transporterAssignments"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminRoleAssigned"
      | "AdminRoleRevoked"
      | "AuditorRoleAssigned"
      | "AuditorRoleRevoked"
      | "BuyerRoleAssigned"
      | "BuyerRoleRevoked"
      | "InspectorRoleAssigned"
      | "InspectorRoleRevoked"
      | "MinerRoleAssigned"
      | "MinerRoleRevoked"
      | "MineralAudited"
      | "MineralInspected"
      | "MineralPurchased"
      | "MineralReadyToTrade"
      | "MineralRefined"
      | "MineralRegistered"
      | "MineralTransported"
      | "RefinerRoleAssigned"
      | "RefinerRoleRevoked"
      | "RoleAdminChanged"
      | "RoleAssigned"
      | "RoleGranted"
      | "RoleRevoked(bytes32,address,address)"
      | "RoleRevoked(bytes32,address,address,uint256)"
      | "TransportAssigned"
      | "TransportCompleted"
      | "TransportRequestCreated"
      | "TransportStatusChanged"
      | "TransporterRoleAssigned"
      | "TransporterRoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BUYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INSPECTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFINER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TRANSPORTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_auditMineral",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "assignAuditor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assignBuyer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assignInspector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assignMiner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assignRefiner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assignTransporter(string,address,uint256)",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignTransporter(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAuditAndInspectionStatus",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "completeTransport",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createTransportRequest",
    values: [string, string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllRoleCounts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMineralHistory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRolesForAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransportDetails",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransportStatus",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransporterAssignments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAdminRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAuditorRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasBuyerRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasInspectorRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasMinerRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRefinerRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasTransporterRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "inspectMineral",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isMineralRegistered",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mineralDetails",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mineralHistories",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseMineral",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "refineMineral",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMineral",
    values: [string, string, BigNumberish, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAuditor",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeBuyer",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeInspector",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeMiner",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRefiner",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTransporter",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "roleMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startTransport",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferMineral",
    values: [string, AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transportDetails",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transporterAssignments",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BUYER_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INSPECTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MINER_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "REFINER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TRANSPORTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_auditMineral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignAuditor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignBuyer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignInspector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignMiner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignRefiner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignTransporter(string,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignTransporter(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAuditAndInspectionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeTransport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTransportRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllRoleCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMineralHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRolesForAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransportDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransportStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransporterAssignments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasAdminRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAuditorRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasBuyerRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasInspectorRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasMinerRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasRefinerRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasTransporterRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inspectMineral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMineralRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mineralDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mineralHistories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseMineral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refineMineral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerMineral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAuditor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeBuyer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeInspector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeMiner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeRefiner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeTransporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startTransport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferMineral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transportDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transporterAssignments",
    data: BytesLike
  ): Result;
}

export namespace AdminRoleAssignedEvent {
  export type InputTuple = [assignee: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [assignee: string, timestamp: bigint];
  export interface OutputObject {
    assignee: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminRoleRevokedEvent {
  export type InputTuple = [
    revokee: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    revokee: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    revokee: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditorRoleAssignedEvent {
  export type InputTuple = [assignee: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [assignee: string, timestamp: bigint];
  export interface OutputObject {
    assignee: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditorRoleRevokedEvent {
  export type InputTuple = [
    revokee: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    revokee: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    revokee: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BuyerRoleAssignedEvent {
  export type InputTuple = [assignee: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [assignee: string, timestamp: bigint];
  export interface OutputObject {
    assignee: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BuyerRoleRevokedEvent {
  export type InputTuple = [
    revokee: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    revokee: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    revokee: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InspectorRoleAssignedEvent {
  export type InputTuple = [assignee: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [assignee: string, timestamp: bigint];
  export interface OutputObject {
    assignee: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InspectorRoleRevokedEvent {
  export type InputTuple = [
    revokee: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    revokee: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    revokee: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinerRoleAssignedEvent {
  export type InputTuple = [assignee: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [assignee: string, timestamp: bigint];
  export interface OutputObject {
    assignee: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinerRoleRevokedEvent {
  export type InputTuple = [
    revokee: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    revokee: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    revokee: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MineralAuditedEvent {
  export type InputTuple = [
    mineralId: string,
    status: string,
    auditor: AddressLike,
    auditedAt: BigNumberish
  ];
  export type OutputTuple = [
    mineralId: string,
    status: string,
    auditor: string,
    auditedAt: bigint
  ];
  export interface OutputObject {
    mineralId: string;
    status: string;
    auditor: string;
    auditedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MineralInspectedEvent {
  export type InputTuple = [
    mineralId: string,
    mineralStatus: string,
    inspector: AddressLike,
    inspectedAt: BigNumberish
  ];
  export type OutputTuple = [
    mineralId: string,
    mineralStatus: string,
    inspector: string,
    inspectedAt: bigint
  ];
  export interface OutputObject {
    mineralId: string;
    mineralStatus: string;
    inspector: string;
    inspectedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MineralPurchasedEvent {
  export type InputTuple = [
    mineralId: string,
    buyer: AddressLike,
    purchasedAt: BigNumberish
  ];
  export type OutputTuple = [
    mineralId: string,
    buyer: string,
    purchasedAt: bigint
  ];
  export interface OutputObject {
    mineralId: string;
    buyer: string;
    purchasedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MineralReadyToTradeEvent {
  export type InputTuple = [
    mineralId: string,
    ApprovedBy: AddressLike,
    status: string,
    inspectionDate: BigNumberish
  ];
  export type OutputTuple = [
    mineralId: string,
    ApprovedBy: string,
    status: string,
    inspectionDate: bigint
  ];
  export interface OutputObject {
    mineralId: string;
    ApprovedBy: string;
    status: string;
    inspectionDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MineralRefinedEvent {
  export type InputTuple = [
    mineralId: string,
    refineryReport: string,
    refiner: AddressLike,
    refinedAt: BigNumberish
  ];
  export type OutputTuple = [
    mineralId: string,
    refineryReport: string,
    refiner: string,
    refinedAt: bigint
  ];
  export interface OutputObject {
    mineralId: string;
    refineryReport: string;
    refiner: string;
    refinedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MineralRegisteredEvent {
  export type InputTuple = [
    mineralId: string,
    mineralName: string,
    mineralType: string,
    origin: string,
    weight: BigNumberish,
    purityPercentage: BigNumberish,
    miner: AddressLike,
    registeredAt: BigNumberish
  ];
  export type OutputTuple = [
    mineralId: string,
    mineralName: string,
    mineralType: string,
    origin: string,
    weight: bigint,
    purityPercentage: bigint,
    miner: string,
    registeredAt: bigint
  ];
  export interface OutputObject {
    mineralId: string;
    mineralName: string;
    mineralType: string;
    origin: string;
    weight: bigint;
    purityPercentage: bigint;
    miner: string;
    registeredAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MineralTransportedEvent {
  export type InputTuple = [
    mineralId: string,
    transporter: AddressLike,
    receivingParty: AddressLike,
    origin: string,
    destination: string,
    transportedAt: BigNumberish
  ];
  export type OutputTuple = [
    mineralId: string,
    transporter: string,
    receivingParty: string,
    origin: string,
    destination: string,
    transportedAt: bigint
  ];
  export interface OutputObject {
    mineralId: string;
    transporter: string;
    receivingParty: string;
    origin: string;
    destination: string;
    transportedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefinerRoleAssignedEvent {
  export type InputTuple = [assignee: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [assignee: string, timestamp: bigint];
  export interface OutputObject {
    assignee: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefinerRoleRevokedEvent {
  export type InputTuple = [
    revokee: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    revokee: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    revokee: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAssignedEvent {
  export type InputTuple = [
    account: AddressLike,
    role: BytesLike,
    roleAssignedAt: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    role: string,
    roleAssignedAt: bigint
  ];
  export interface OutputObject {
    account: string;
    role: string;
    roleAssignedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevoked_bytes32_address_address_Event {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevoked_bytes32_address_address_uint256_Event {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    revoker: AddressLike,
    roleRevokedAt: BigNumberish
  ];
  export type OutputTuple = [
    role: string,
    account: string,
    revoker: string,
    roleRevokedAt: bigint
  ];
  export interface OutputObject {
    role: string;
    account: string;
    revoker: string;
    roleRevokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransportAssignedEvent {
  export type InputTuple = [
    mineralId: string,
    transporter: AddressLike,
    assignedAt: BigNumberish
  ];
  export type OutputTuple = [
    mineralId: string,
    transporter: string,
    assignedAt: bigint
  ];
  export interface OutputObject {
    mineralId: string;
    transporter: string;
    assignedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransportCompletedEvent {
  export type InputTuple = [
    mineralId: string,
    transporter: AddressLike,
    completedAt: BigNumberish
  ];
  export type OutputTuple = [
    mineralId: string,
    transporter: string,
    completedAt: bigint
  ];
  export interface OutputObject {
    mineralId: string;
    transporter: string;
    completedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransportRequestCreatedEvent {
  export type InputTuple = [
    mineralId: string,
    requester: AddressLike,
    origin: string,
    destination: string,
    estimatedDeparture: BigNumberish,
    requestTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    mineralId: string,
    requester: string,
    origin: string,
    destination: string,
    estimatedDeparture: bigint,
    requestTimestamp: bigint
  ];
  export interface OutputObject {
    mineralId: string;
    requester: string;
    origin: string;
    destination: string;
    estimatedDeparture: bigint;
    requestTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransportStatusChangedEvent {
  export type InputTuple = [
    mineralId: string,
    newStatus: string,
    updatedAt: BigNumberish
  ];
  export type OutputTuple = [
    mineralId: string,
    newStatus: string,
    updatedAt: bigint
  ];
  export interface OutputObject {
    mineralId: string;
    newStatus: string;
    updatedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransporterRoleAssignedEvent {
  export type InputTuple = [assignee: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [assignee: string, timestamp: bigint];
  export interface OutputObject {
    assignee: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransporterRoleRevokedEvent {
  export type InputTuple = [
    revokee: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    revokee: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    revokee: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LogisticsManager extends BaseContract {
  connect(runner?: ContractRunner | null): LogisticsManager;
  waitForDeployment(): Promise<this>;

  interface: LogisticsManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AUDITOR_ROLE: TypedContractMethod<[], [string], "view">;

  BUYER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  INSPECTOR_ROLE: TypedContractMethod<[], [string], "view">;

  MINER_ROLE: TypedContractMethod<[], [string], "view">;

  REFINER_ROLE: TypedContractMethod<[], [string], "view">;

  TRANSPORTER_ROLE: TypedContractMethod<[], [string], "view">;

  _auditMineral: TypedContractMethod<
    [mineralId: string, report: string],
    [void],
    "nonpayable"
  >;

  assignAuditor: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  assignBuyer: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  assignInspector: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  assignMiner: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  assignRefiner: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  "assignTransporter(string,address,uint256)": TypedContractMethod<
    [
      mineralId: string,
      transporter: AddressLike,
      estimatedArrival: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "assignTransporter(address)": TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  checkAuditAndInspectionStatus: TypedContractMethod<
    [mineralId: string],
    [[boolean, boolean] & { isAudited: boolean; isInspected: boolean }],
    "nonpayable"
  >;

  completeTransport: TypedContractMethod<
    [mineralId: string],
    [void],
    "nonpayable"
  >;

  createTransportRequest: TypedContractMethod<
    [
      mineralId: string,
      origin: string,
      destination: string,
      estimatedDeparture: BigNumberish,
      transportConditions: string
    ],
    [void],
    "nonpayable"
  >;

  getAllRoleCounts: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        minerCount: bigint;
        refinerCount: bigint;
        transporterCount: bigint;
        auditorCount: bigint;
        inspectorCount: bigint;
        buyerCount: bigint;
      }
    ],
    "view"
  >;

  getMineralHistory: TypedContractMethod<
    [mineralId: string],
    [RolesManager.MineralHistoryStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getRoleMemberCount: TypedContractMethod<[role: BytesLike], [bigint], "view">;

  getRolesForAddress: TypedContractMethod<
    [account: AddressLike],
    [string[]],
    "view"
  >;

  getTransportDetails: TypedContractMethod<
    [mineralId: string],
    [LogisticsManager.TransportDetailsStructOutput],
    "view"
  >;

  getTransportStatus: TypedContractMethod<
    [mineralId: string],
    [string],
    "view"
  >;

  getTransporterAssignments: TypedContractMethod<
    [transporter: AddressLike],
    [string[]],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasAdminRole: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  hasAuditorRole: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  hasBuyerRole: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  hasInspectorRole: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  hasMinerRole: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  hasRefinerRole: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hasTransporterRole: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  inspectMineral: TypedContractMethod<
    [mineralId: string, report: string],
    [void],
    "nonpayable"
  >;

  isMineralRegistered: TypedContractMethod<
    [mineralId: string],
    [boolean],
    "nonpayable"
  >;

  mineralDetails: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        string,
        boolean,
        boolean,
        boolean,
        boolean,
        bigint
      ] & {
        id: string;
        name: string;
        origin: string;
        mineralType: string;
        weight: bigint;
        purityPercentage: bigint;
        storageConditions: string;
        registeredBy: string;
        currentStatus: string;
        currentLocation: string;
        currentHandler: string;
        isPurchased: boolean;
        isRefined: boolean;
        isAudited: boolean;
        isInspected: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  mineralHistories: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        id: string;
        fieldChanged: string;
        newValue: string;
        updatedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  purchaseMineral: TypedContractMethod<
    [mineralId: string],
    [void],
    "nonpayable"
  >;

  refineMineral: TypedContractMethod<
    [mineralId: string, report: string],
    [void],
    "nonpayable"
  >;

  registerMineral: TypedContractMethod<
    [
      _name: string,
      _mineralType: string,
      _weight: BigNumberish,
      _origin: string,
      _purityPercentage: BigNumberish,
      _storageConditions: string
    ],
    [string],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeAuditor: TypedContractMethod<
    [account: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  revokeBuyer: TypedContractMethod<
    [account: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  revokeInspector: TypedContractMethod<
    [account: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  revokeMiner: TypedContractMethod<
    [account: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  revokeRefiner: TypedContractMethod<
    [account: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeTransporter: TypedContractMethod<
    [account: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  roleMemberCount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  startTransport: TypedContractMethod<
    [mineralId: string],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferMineral: TypedContractMethod<
    [
      mineralId: string,
      _receivingParty: AddressLike,
      _origin: string,
      _destination: string
    ],
    [void],
    "nonpayable"
  >;

  transportDetails: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        mineralId: string;
        requester: string;
        transporter: string;
        origin: string;
        destination: string;
        estimatedDeparture: bigint;
        actualDeparture: bigint;
        estimatedArrival: bigint;
        actualArrival: bigint;
        currentStatus: string;
        transportConditions: string;
      }
    ],
    "view"
  >;

  transporterAssignments: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AUDITOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BUYER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INSPECTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MINER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REFINER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TRANSPORTER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "_auditMineral"
  ): TypedContractMethod<
    [mineralId: string, report: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assignAuditor"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignBuyer"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignInspector"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignMiner"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignRefiner"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignTransporter(string,address,uint256)"
  ): TypedContractMethod<
    [
      mineralId: string,
      transporter: AddressLike,
      estimatedArrival: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assignTransporter(address)"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkAuditAndInspectionStatus"
  ): TypedContractMethod<
    [mineralId: string],
    [[boolean, boolean] & { isAudited: boolean; isInspected: boolean }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "completeTransport"
  ): TypedContractMethod<[mineralId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTransportRequest"
  ): TypedContractMethod<
    [
      mineralId: string,
      origin: string,
      destination: string,
      estimatedDeparture: BigNumberish,
      transportConditions: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllRoleCounts"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        minerCount: bigint;
        refinerCount: bigint;
        transporterCount: bigint;
        auditorCount: bigint;
        inspectorCount: bigint;
        buyerCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMineralHistory"
  ): TypedContractMethod<
    [mineralId: string],
    [RolesManager.MineralHistoryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleMemberCount"
  ): TypedContractMethod<[role: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRolesForAddress"
  ): TypedContractMethod<[account: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTransportDetails"
  ): TypedContractMethod<
    [mineralId: string],
    [LogisticsManager.TransportDetailsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransportStatus"
  ): TypedContractMethod<[mineralId: string], [string], "view">;
  getFunction(
    nameOrSignature: "getTransporterAssignments"
  ): TypedContractMethod<[transporter: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasAdminRole"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasAuditorRole"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasBuyerRole"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasInspectorRole"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasMinerRole"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasRefinerRole"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasTransporterRole"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "inspectMineral"
  ): TypedContractMethod<
    [mineralId: string, report: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isMineralRegistered"
  ): TypedContractMethod<[mineralId: string], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "mineralDetails"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        string,
        boolean,
        boolean,
        boolean,
        boolean,
        bigint
      ] & {
        id: string;
        name: string;
        origin: string;
        mineralType: string;
        weight: bigint;
        purityPercentage: bigint;
        storageConditions: string;
        registeredBy: string;
        currentStatus: string;
        currentLocation: string;
        currentHandler: string;
        isPurchased: boolean;
        isRefined: boolean;
        isAudited: boolean;
        isInspected: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "mineralHistories"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, string, string, bigint] & {
        id: string;
        fieldChanged: string;
        newValue: string;
        updatedBy: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "purchaseMineral"
  ): TypedContractMethod<[mineralId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refineMineral"
  ): TypedContractMethod<
    [mineralId: string, report: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerMineral"
  ): TypedContractMethod<
    [
      _name: string,
      _mineralType: string,
      _weight: BigNumberish,
      _origin: string,
      _purityPercentage: BigNumberish,
      _storageConditions: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAuditor"
  ): TypedContractMethod<
    [account: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeBuyer"
  ): TypedContractMethod<
    [account: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeInspector"
  ): TypedContractMethod<
    [account: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeMiner"
  ): TypedContractMethod<
    [account: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRefiner"
  ): TypedContractMethod<
    [account: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeTransporter"
  ): TypedContractMethod<
    [account: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleMemberCount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "startTransport"
  ): TypedContractMethod<[mineralId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferMineral"
  ): TypedContractMethod<
    [
      mineralId: string,
      _receivingParty: AddressLike,
      _origin: string,
      _destination: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transportDetails"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        mineralId: string;
        requester: string;
        transporter: string;
        origin: string;
        destination: string;
        estimatedDeparture: bigint;
        actualDeparture: bigint;
        estimatedArrival: bigint;
        actualArrival: bigint;
        currentStatus: string;
        transportConditions: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transporterAssignments"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "AdminRoleAssigned"
  ): TypedContractEvent<
    AdminRoleAssignedEvent.InputTuple,
    AdminRoleAssignedEvent.OutputTuple,
    AdminRoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "AdminRoleRevoked"
  ): TypedContractEvent<
    AdminRoleRevokedEvent.InputTuple,
    AdminRoleRevokedEvent.OutputTuple,
    AdminRoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "AuditorRoleAssigned"
  ): TypedContractEvent<
    AuditorRoleAssignedEvent.InputTuple,
    AuditorRoleAssignedEvent.OutputTuple,
    AuditorRoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "AuditorRoleRevoked"
  ): TypedContractEvent<
    AuditorRoleRevokedEvent.InputTuple,
    AuditorRoleRevokedEvent.OutputTuple,
    AuditorRoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "BuyerRoleAssigned"
  ): TypedContractEvent<
    BuyerRoleAssignedEvent.InputTuple,
    BuyerRoleAssignedEvent.OutputTuple,
    BuyerRoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "BuyerRoleRevoked"
  ): TypedContractEvent<
    BuyerRoleRevokedEvent.InputTuple,
    BuyerRoleRevokedEvent.OutputTuple,
    BuyerRoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "InspectorRoleAssigned"
  ): TypedContractEvent<
    InspectorRoleAssignedEvent.InputTuple,
    InspectorRoleAssignedEvent.OutputTuple,
    InspectorRoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "InspectorRoleRevoked"
  ): TypedContractEvent<
    InspectorRoleRevokedEvent.InputTuple,
    InspectorRoleRevokedEvent.OutputTuple,
    InspectorRoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "MinerRoleAssigned"
  ): TypedContractEvent<
    MinerRoleAssignedEvent.InputTuple,
    MinerRoleAssignedEvent.OutputTuple,
    MinerRoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "MinerRoleRevoked"
  ): TypedContractEvent<
    MinerRoleRevokedEvent.InputTuple,
    MinerRoleRevokedEvent.OutputTuple,
    MinerRoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "MineralAudited"
  ): TypedContractEvent<
    MineralAuditedEvent.InputTuple,
    MineralAuditedEvent.OutputTuple,
    MineralAuditedEvent.OutputObject
  >;
  getEvent(
    key: "MineralInspected"
  ): TypedContractEvent<
    MineralInspectedEvent.InputTuple,
    MineralInspectedEvent.OutputTuple,
    MineralInspectedEvent.OutputObject
  >;
  getEvent(
    key: "MineralPurchased"
  ): TypedContractEvent<
    MineralPurchasedEvent.InputTuple,
    MineralPurchasedEvent.OutputTuple,
    MineralPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "MineralReadyToTrade"
  ): TypedContractEvent<
    MineralReadyToTradeEvent.InputTuple,
    MineralReadyToTradeEvent.OutputTuple,
    MineralReadyToTradeEvent.OutputObject
  >;
  getEvent(
    key: "MineralRefined"
  ): TypedContractEvent<
    MineralRefinedEvent.InputTuple,
    MineralRefinedEvent.OutputTuple,
    MineralRefinedEvent.OutputObject
  >;
  getEvent(
    key: "MineralRegistered"
  ): TypedContractEvent<
    MineralRegisteredEvent.InputTuple,
    MineralRegisteredEvent.OutputTuple,
    MineralRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MineralTransported"
  ): TypedContractEvent<
    MineralTransportedEvent.InputTuple,
    MineralTransportedEvent.OutputTuple,
    MineralTransportedEvent.OutputObject
  >;
  getEvent(
    key: "RefinerRoleAssigned"
  ): TypedContractEvent<
    RefinerRoleAssignedEvent.InputTuple,
    RefinerRoleAssignedEvent.OutputTuple,
    RefinerRoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "RefinerRoleRevoked"
  ): TypedContractEvent<
    RefinerRoleRevokedEvent.InputTuple,
    RefinerRoleRevokedEvent.OutputTuple,
    RefinerRoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAssigned"
  ): TypedContractEvent<
    RoleAssignedEvent.InputTuple,
    RoleAssignedEvent.OutputTuple,
    RoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked(bytes32,address,address)"
  ): TypedContractEvent<
    RoleRevoked_bytes32_address_address_Event.InputTuple,
    RoleRevoked_bytes32_address_address_Event.OutputTuple,
    RoleRevoked_bytes32_address_address_Event.OutputObject
  >;
  getEvent(
    key: "RoleRevoked(bytes32,address,address,uint256)"
  ): TypedContractEvent<
    RoleRevoked_bytes32_address_address_uint256_Event.InputTuple,
    RoleRevoked_bytes32_address_address_uint256_Event.OutputTuple,
    RoleRevoked_bytes32_address_address_uint256_Event.OutputObject
  >;
  getEvent(
    key: "TransportAssigned"
  ): TypedContractEvent<
    TransportAssignedEvent.InputTuple,
    TransportAssignedEvent.OutputTuple,
    TransportAssignedEvent.OutputObject
  >;
  getEvent(
    key: "TransportCompleted"
  ): TypedContractEvent<
    TransportCompletedEvent.InputTuple,
    TransportCompletedEvent.OutputTuple,
    TransportCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TransportRequestCreated"
  ): TypedContractEvent<
    TransportRequestCreatedEvent.InputTuple,
    TransportRequestCreatedEvent.OutputTuple,
    TransportRequestCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TransportStatusChanged"
  ): TypedContractEvent<
    TransportStatusChangedEvent.InputTuple,
    TransportStatusChangedEvent.OutputTuple,
    TransportStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "TransporterRoleAssigned"
  ): TypedContractEvent<
    TransporterRoleAssignedEvent.InputTuple,
    TransporterRoleAssignedEvent.OutputTuple,
    TransporterRoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "TransporterRoleRevoked"
  ): TypedContractEvent<
    TransporterRoleRevokedEvent.InputTuple,
    TransporterRoleRevokedEvent.OutputTuple,
    TransporterRoleRevokedEvent.OutputObject
  >;

  filters: {
    "AdminRoleAssigned(address,uint256)": TypedContractEvent<
      AdminRoleAssignedEvent.InputTuple,
      AdminRoleAssignedEvent.OutputTuple,
      AdminRoleAssignedEvent.OutputObject
    >;
    AdminRoleAssigned: TypedContractEvent<
      AdminRoleAssignedEvent.InputTuple,
      AdminRoleAssignedEvent.OutputTuple,
      AdminRoleAssignedEvent.OutputObject
    >;

    "AdminRoleRevoked(address,string,uint256)": TypedContractEvent<
      AdminRoleRevokedEvent.InputTuple,
      AdminRoleRevokedEvent.OutputTuple,
      AdminRoleRevokedEvent.OutputObject
    >;
    AdminRoleRevoked: TypedContractEvent<
      AdminRoleRevokedEvent.InputTuple,
      AdminRoleRevokedEvent.OutputTuple,
      AdminRoleRevokedEvent.OutputObject
    >;

    "AuditorRoleAssigned(address,uint256)": TypedContractEvent<
      AuditorRoleAssignedEvent.InputTuple,
      AuditorRoleAssignedEvent.OutputTuple,
      AuditorRoleAssignedEvent.OutputObject
    >;
    AuditorRoleAssigned: TypedContractEvent<
      AuditorRoleAssignedEvent.InputTuple,
      AuditorRoleAssignedEvent.OutputTuple,
      AuditorRoleAssignedEvent.OutputObject
    >;

    "AuditorRoleRevoked(address,string,uint256)": TypedContractEvent<
      AuditorRoleRevokedEvent.InputTuple,
      AuditorRoleRevokedEvent.OutputTuple,
      AuditorRoleRevokedEvent.OutputObject
    >;
    AuditorRoleRevoked: TypedContractEvent<
      AuditorRoleRevokedEvent.InputTuple,
      AuditorRoleRevokedEvent.OutputTuple,
      AuditorRoleRevokedEvent.OutputObject
    >;

    "BuyerRoleAssigned(address,uint256)": TypedContractEvent<
      BuyerRoleAssignedEvent.InputTuple,
      BuyerRoleAssignedEvent.OutputTuple,
      BuyerRoleAssignedEvent.OutputObject
    >;
    BuyerRoleAssigned: TypedContractEvent<
      BuyerRoleAssignedEvent.InputTuple,
      BuyerRoleAssignedEvent.OutputTuple,
      BuyerRoleAssignedEvent.OutputObject
    >;

    "BuyerRoleRevoked(address,string,uint256)": TypedContractEvent<
      BuyerRoleRevokedEvent.InputTuple,
      BuyerRoleRevokedEvent.OutputTuple,
      BuyerRoleRevokedEvent.OutputObject
    >;
    BuyerRoleRevoked: TypedContractEvent<
      BuyerRoleRevokedEvent.InputTuple,
      BuyerRoleRevokedEvent.OutputTuple,
      BuyerRoleRevokedEvent.OutputObject
    >;

    "InspectorRoleAssigned(address,uint256)": TypedContractEvent<
      InspectorRoleAssignedEvent.InputTuple,
      InspectorRoleAssignedEvent.OutputTuple,
      InspectorRoleAssignedEvent.OutputObject
    >;
    InspectorRoleAssigned: TypedContractEvent<
      InspectorRoleAssignedEvent.InputTuple,
      InspectorRoleAssignedEvent.OutputTuple,
      InspectorRoleAssignedEvent.OutputObject
    >;

    "InspectorRoleRevoked(address,string,uint256)": TypedContractEvent<
      InspectorRoleRevokedEvent.InputTuple,
      InspectorRoleRevokedEvent.OutputTuple,
      InspectorRoleRevokedEvent.OutputObject
    >;
    InspectorRoleRevoked: TypedContractEvent<
      InspectorRoleRevokedEvent.InputTuple,
      InspectorRoleRevokedEvent.OutputTuple,
      InspectorRoleRevokedEvent.OutputObject
    >;

    "MinerRoleAssigned(address,uint256)": TypedContractEvent<
      MinerRoleAssignedEvent.InputTuple,
      MinerRoleAssignedEvent.OutputTuple,
      MinerRoleAssignedEvent.OutputObject
    >;
    MinerRoleAssigned: TypedContractEvent<
      MinerRoleAssignedEvent.InputTuple,
      MinerRoleAssignedEvent.OutputTuple,
      MinerRoleAssignedEvent.OutputObject
    >;

    "MinerRoleRevoked(address,string,uint256)": TypedContractEvent<
      MinerRoleRevokedEvent.InputTuple,
      MinerRoleRevokedEvent.OutputTuple,
      MinerRoleRevokedEvent.OutputObject
    >;
    MinerRoleRevoked: TypedContractEvent<
      MinerRoleRevokedEvent.InputTuple,
      MinerRoleRevokedEvent.OutputTuple,
      MinerRoleRevokedEvent.OutputObject
    >;

    "MineralAudited(string,string,address,uint256)": TypedContractEvent<
      MineralAuditedEvent.InputTuple,
      MineralAuditedEvent.OutputTuple,
      MineralAuditedEvent.OutputObject
    >;
    MineralAudited: TypedContractEvent<
      MineralAuditedEvent.InputTuple,
      MineralAuditedEvent.OutputTuple,
      MineralAuditedEvent.OutputObject
    >;

    "MineralInspected(string,string,address,uint256)": TypedContractEvent<
      MineralInspectedEvent.InputTuple,
      MineralInspectedEvent.OutputTuple,
      MineralInspectedEvent.OutputObject
    >;
    MineralInspected: TypedContractEvent<
      MineralInspectedEvent.InputTuple,
      MineralInspectedEvent.OutputTuple,
      MineralInspectedEvent.OutputObject
    >;

    "MineralPurchased(string,address,uint256)": TypedContractEvent<
      MineralPurchasedEvent.InputTuple,
      MineralPurchasedEvent.OutputTuple,
      MineralPurchasedEvent.OutputObject
    >;
    MineralPurchased: TypedContractEvent<
      MineralPurchasedEvent.InputTuple,
      MineralPurchasedEvent.OutputTuple,
      MineralPurchasedEvent.OutputObject
    >;

    "MineralReadyToTrade(string,address,string,uint256)": TypedContractEvent<
      MineralReadyToTradeEvent.InputTuple,
      MineralReadyToTradeEvent.OutputTuple,
      MineralReadyToTradeEvent.OutputObject
    >;
    MineralReadyToTrade: TypedContractEvent<
      MineralReadyToTradeEvent.InputTuple,
      MineralReadyToTradeEvent.OutputTuple,
      MineralReadyToTradeEvent.OutputObject
    >;

    "MineralRefined(string,string,address,uint256)": TypedContractEvent<
      MineralRefinedEvent.InputTuple,
      MineralRefinedEvent.OutputTuple,
      MineralRefinedEvent.OutputObject
    >;
    MineralRefined: TypedContractEvent<
      MineralRefinedEvent.InputTuple,
      MineralRefinedEvent.OutputTuple,
      MineralRefinedEvent.OutputObject
    >;

    "MineralRegistered(string,string,string,string,uint256,uint256,address,uint256)": TypedContractEvent<
      MineralRegisteredEvent.InputTuple,
      MineralRegisteredEvent.OutputTuple,
      MineralRegisteredEvent.OutputObject
    >;
    MineralRegistered: TypedContractEvent<
      MineralRegisteredEvent.InputTuple,
      MineralRegisteredEvent.OutputTuple,
      MineralRegisteredEvent.OutputObject
    >;

    "MineralTransported(string,address,address,string,string,uint256)": TypedContractEvent<
      MineralTransportedEvent.InputTuple,
      MineralTransportedEvent.OutputTuple,
      MineralTransportedEvent.OutputObject
    >;
    MineralTransported: TypedContractEvent<
      MineralTransportedEvent.InputTuple,
      MineralTransportedEvent.OutputTuple,
      MineralTransportedEvent.OutputObject
    >;

    "RefinerRoleAssigned(address,uint256)": TypedContractEvent<
      RefinerRoleAssignedEvent.InputTuple,
      RefinerRoleAssignedEvent.OutputTuple,
      RefinerRoleAssignedEvent.OutputObject
    >;
    RefinerRoleAssigned: TypedContractEvent<
      RefinerRoleAssignedEvent.InputTuple,
      RefinerRoleAssignedEvent.OutputTuple,
      RefinerRoleAssignedEvent.OutputObject
    >;

    "RefinerRoleRevoked(address,string,uint256)": TypedContractEvent<
      RefinerRoleRevokedEvent.InputTuple,
      RefinerRoleRevokedEvent.OutputTuple,
      RefinerRoleRevokedEvent.OutputObject
    >;
    RefinerRoleRevoked: TypedContractEvent<
      RefinerRoleRevokedEvent.InputTuple,
      RefinerRoleRevokedEvent.OutputTuple,
      RefinerRoleRevokedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleAssigned(address,bytes32,uint256)": TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;
    RoleAssigned: TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevoked_bytes32_address_address_Event.InputTuple,
      RoleRevoked_bytes32_address_address_Event.OutputTuple,
      RoleRevoked_bytes32_address_address_Event.OutputObject
    >;
    "RoleRevoked(bytes32,address,address,uint256)": TypedContractEvent<
      RoleRevoked_bytes32_address_address_uint256_Event.InputTuple,
      RoleRevoked_bytes32_address_address_uint256_Event.OutputTuple,
      RoleRevoked_bytes32_address_address_uint256_Event.OutputObject
    >;

    "TransportAssigned(string,address,uint256)": TypedContractEvent<
      TransportAssignedEvent.InputTuple,
      TransportAssignedEvent.OutputTuple,
      TransportAssignedEvent.OutputObject
    >;
    TransportAssigned: TypedContractEvent<
      TransportAssignedEvent.InputTuple,
      TransportAssignedEvent.OutputTuple,
      TransportAssignedEvent.OutputObject
    >;

    "TransportCompleted(string,address,uint256)": TypedContractEvent<
      TransportCompletedEvent.InputTuple,
      TransportCompletedEvent.OutputTuple,
      TransportCompletedEvent.OutputObject
    >;
    TransportCompleted: TypedContractEvent<
      TransportCompletedEvent.InputTuple,
      TransportCompletedEvent.OutputTuple,
      TransportCompletedEvent.OutputObject
    >;

    "TransportRequestCreated(string,address,string,string,uint256,uint256)": TypedContractEvent<
      TransportRequestCreatedEvent.InputTuple,
      TransportRequestCreatedEvent.OutputTuple,
      TransportRequestCreatedEvent.OutputObject
    >;
    TransportRequestCreated: TypedContractEvent<
      TransportRequestCreatedEvent.InputTuple,
      TransportRequestCreatedEvent.OutputTuple,
      TransportRequestCreatedEvent.OutputObject
    >;

    "TransportStatusChanged(string,string,uint256)": TypedContractEvent<
      TransportStatusChangedEvent.InputTuple,
      TransportStatusChangedEvent.OutputTuple,
      TransportStatusChangedEvent.OutputObject
    >;
    TransportStatusChanged: TypedContractEvent<
      TransportStatusChangedEvent.InputTuple,
      TransportStatusChangedEvent.OutputTuple,
      TransportStatusChangedEvent.OutputObject
    >;

    "TransporterRoleAssigned(address,uint256)": TypedContractEvent<
      TransporterRoleAssignedEvent.InputTuple,
      TransporterRoleAssignedEvent.OutputTuple,
      TransporterRoleAssignedEvent.OutputObject
    >;
    TransporterRoleAssigned: TypedContractEvent<
      TransporterRoleAssignedEvent.InputTuple,
      TransporterRoleAssignedEvent.OutputTuple,
      TransporterRoleAssignedEvent.OutputObject
    >;

    "TransporterRoleRevoked(address,string,uint256)": TypedContractEvent<
      TransporterRoleRevokedEvent.InputTuple,
      TransporterRoleRevokedEvent.OutputTuple,
      TransporterRoleRevokedEvent.OutputObject
    >;
    TransporterRoleRevoked: TypedContractEvent<
      TransporterRoleRevokedEvent.InputTuple,
      TransporterRoleRevokedEvent.OutputTuple,
      TransporterRoleRevokedEvent.OutputObject
    >;
  };
}
